version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

volumes:
  postgres_data:
